---
- name: win_ping_test
  hosts: all
  tasks:
    - name: Debug Messages
      debug:
        msg: 
          - "Ansible Facts"
          - "ansible_user = {{ ansible_user }}"

  roles:
    - win_ping_test
      