---
- name: win_ping_test
  hosts: all
  tasks:
    - name: Debug Messages
      debug:
        msg: 
          - "Ansible Facts"
          - "ansible_user = {{ ansible_user }}"

    - name: Debug hostvars
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 4

  roles:
    - win_ping_test
      