---
- name: win_ping_test
  hosts: all
  tasks:
    - name: Debug Messages
      debug:
        msg: 
          - "Ansible Facts"
          - "{{ ansible_user }}"

    - name: Print out all morpheus vars
      debug: 
        msg: 
        - "This is the morpheus json vars"
        - "{{ hostvars[inventory_hostname]['morpheus']['server'] | to_nice_json | deault({})}}"

  roles:
    - win_ping_test
      