---
- name: win_ping_test
  hosts: all
  tasks:
    - name: Debug Messages
      debug:
        msg: 
          - "Ansible Facts"
          - "ansible_user = {{ ansible_user }}"

    - name: Print out all morpheus vars
      debug: 
        msg: "{{ hostvars[inventory_hostname]['morpheus']['server'] | to_yaml }}"

  roles:
    - win_ping_test
      